// <auto-generated />
using System;
using AnimaisExtincaoAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalsApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("AnimaisExtincaoAPI.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dieta")
                        .HasColumnType("TEXT");

                    b.Property<string>("Familia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Habitat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCientifico")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ordem")
                        .HasColumnType("TEXT");

                    b.Property<double?>("PesoMedio")
                        .HasColumnType("REAL");

                    b.Property<int?>("PopulacaoEstimada")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrincipaisAmeacas")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusConservacao")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Tamanho")
                        .HasColumnType("REAL");

                    b.Property<string>("TendenciaPopulacional")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Animais");
                });
#pragma warning restore 612, 618
        }
    }
}
